version: '3.8'

services:

  db:
    image: postgres:15.3-alpine
    container_name: postgresDBRestaurant
    restart: always
    volumes:
      - "postgresDataRestaurant:/var/lib/postgresql/data:rw"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    container_name: appRestaurant
    restart: always
    build:
      context: ./..
      dockerfile: app/Dockerfile
    depends_on:
      - db
    command: ["python", "main.py"]
    ports:
      - "${APP_PORT}:6000"
    volumes:
      - "../app:/usr/app:rw"
    environment:
      - SERVER_NAME=appRestaurant
      - DEBUG=${APP_DEBUG}
      - PORT=${APP_PORT}

      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

      - DB_PORT=${POSTGRES_PORT}
      - DB_HOST=postgresDBRestaurant

volumes:
  postgresDataRestaurant:
